#!/usr/bin/env python3
"""
Structural check on the Kotlin sources, for an environment with no compiler.

This is not a type checker and does not pretend to be. It catches the class of
mistake that a careful reader misses and a compiler would have caught instantly:
an unbalanced brace inside a raw string, a file whose package disagrees with its
directory, an import of a class that does not exist in the project, a stray
Kotlin interpolation in a JS template.

Usage: python3 tools/verify_kotlin.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_ROOTS = [
    os.path.join(ROOT, "app", "src", "main", "java"),
    os.path.join(ROOT, "app", "src", "test", "java"),
]
PKG = "com.threadbare.client"

# Generated by AGP at build time, so they are never declared in source.
GENERATED = {PKG + ".R", PKG + ".BuildConfig"}

FAILURES = []


def fail(path, msg):
    FAILURES.append("%s: %s" % (os.path.relpath(path, ROOT), msg))


def strip_code(text):
    """
    Return the source with comments, string literals and char literals blanked,
    preserving newlines so line numbers still line up.

    Handles raw strings (\"\"\"...\"\"\"), escapes, backtick identifiers and
    nested block comments — Kotlin allows comment nesting, and a naive scanner
    gets the balance wrong on the first nested one.
    """
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        two = text[i:i + 2]
        three = text[i:i + 3]

        if three == '"""':
            j = text.find('"""', i + 3)
            j = n if j == -1 else j + 3
            out.append("".join(ch if ch == "\n" else " " for ch in text[i:j]))
            i = j
            continue
        if c == '"':
            j = i + 1
            while j < n and text[j] != '"':
                if text[j] == "\\":
                    j += 1
                if text[j:j + 1] == "\n":
                    break
                j += 1
            j = min(j + 1, n)
            out.append(" " * (j - i))
            i = j
            continue
        if c == "`":
            # A backtick identifier — Kotlin test names are full of them, and
            # they routinely contain apostrophes ("reddit's own ..."). Without
            # this case the apostrophe opens a phantom char literal that eats
            # everything up to the next one, braces included, and the balance
            # check reports a fault many lines away from anything real.
            j = text.find("`", i + 1)
            j = n if j == -1 else j + 1
            out.append(" " * (j - i))
            i = j
            continue
        if c == "'":
            j = i + 1
            while j < n and text[j] != "'":
                if text[j] == "\\":
                    j += 1
                j += 1
            j = min(j + 1, n)
            out.append(" " * (j - i))
            i = j
            continue
        if two == "//":
            j = text.find("\n", i)
            j = n if j == -1 else j
            out.append(" " * (j - i))
            i = j
            continue
        if two == "/*":
            depth, j = 1, i + 2
            while j < n and depth:
                if text[j:j + 2] == "/*":
                    depth += 1
                    j += 2
                elif text[j:j + 2] == "*/":
                    depth -= 1
                    j += 2
                else:
                    j += 1
            out.append("".join(ch if ch == "\n" else " " for ch in text[i:j]))
            i = j
            continue

        out.append(c)
        i += 1
    return "".join(out)


def kotlin_files():
    for root_dir in SRC_ROOTS:
        for dirpath, _, names in os.walk(root_dir):
            for name in names:
                if name.endswith(".kt"):
                    yield os.path.join(dirpath, name), root_dir


def main():
    declared = {}  # fully-qualified name -> path
    files = list(kotlin_files())
    if not files:
        print("no Kotlin sources found")
        return 1

    for path, src_root in files:
        text = open(path, encoding="utf-8").read()
        code = strip_code(text)

        # ---- delimiter balance
        for open_ch, close_ch, label in (("{", "}", "brace"),
                                         ("(", ")", "paren"),
                                         ("[", "]", "bracket")):
            depth = 0
            for ch in code:
                if ch == open_ch:
                    depth += 1
                elif ch == close_ch:
                    depth -= 1
                    if depth < 0:
                        break
            if depth != 0:
                fail(path, "unbalanced %s (net %+d)" % (label, depth))

        # ---- package agrees with directory
        m = re.search(r"^\s*package\s+([\w.]+)", code, re.M)
        if not m:
            fail(path, "no package declaration")
            continue
        package = m.group(1)
        expected_dir = os.path.join(src_root, *package.split("."))
        if os.path.dirname(os.path.abspath(path)) != os.path.abspath(expected_dir):
            fail(path, "package %s does not match its directory" % package)

        # ---- record top-level declarations
        for kind, name in re.findall(
            r"^\s*(?:public\s+|internal\s+|private\s+|abstract\s+|open\s+|sealed\s+|data\s+|enum\s+)*"
            r"(class|object|interface|enum class)\s+(\w+)", code, re.M
        ):
            declared["%s.%s" % (package, name)] = path

    # ---- in-project imports resolve
    for path, _ in files:
        code = strip_code(open(path, encoding="utf-8").read())
        for imp in re.findall(r"^\s*import\s+([\w.]+)", code, re.M):
            if not imp.startswith(PKG):
                continue
            if imp in declared or imp in GENERATED:
                continue
            # A member import (Prefs.KEY_X) resolves if its owner does.
            owner = imp.rsplit(".", 1)[0]
            if owner in declared or owner in GENERATED:
                continue
            fail(path, "import %s does not resolve to anything in the project" % imp)

    # ---- no unsubstituted interpolation left in a JS template
    scripts = os.path.join(ROOT, "app", "src", "main", "java", "com", "threadbare",
                           "client", "web", "SiteScripts.kt")
    if os.path.exists(scripts):
        text = open(scripts, encoding="utf-8").read()
        for block in re.findall(r'"""(.*?)"""', text, re.S):
            for var in re.findall(r"\$\{(\w+)", block):
                if var not in ("jsString", "textScalePercent", "major", "css"):
                    fail(scripts, "raw string interpolates unknown '%s'" % var)

    print("checked %d Kotlin files, %d top-level declarations" % (len(files), len(declared)))
    if FAILURES:
        for f in FAILURES:
            print("FAIL  %s" % f)
        print("\n%d failures" % len(FAILURES))
        return 1
    print("clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
